Update authentication headers example in README
algonauti/ember-active-storage pull request #22
Opened 2018-12-05 15:34 UTC by algodave

At the time of writing the Readme, Ember Simple Auth supported a different way of grabbing authentication headers. In this PR I'm describing the updated way.

2018-12-05 16:01 UTC, safeforge approved these changes

2018-12-17 09:54 UTC, safeforge requested changes
@algodave can you rebase after #23 - test should be fixed

2018-12-19 11:07 UTC, safeforge approved these changes

2018-12-19 11:07 UTC, merged

2018-12-19 14:01 UTC, algodave commented
thanks for rebasing @safeforge